version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cc:e2:e9:73:f0:17:71:8a:fd:89:05:50:7c:30:6c:53"
      - checkout
      - run: ./deploy.sh
